- src/components/layout/PageHeader/index.tsx
- src/components/ui/Card/index.tsx
- src/components/ui/InfoBanner/index.tsx
- src/components/ui/SmallCard/index.tsx
- src/components/utilities/Button/index.tsx
- src/pages/community.tsx
- src/pages/features.tsx
- src/pages/index.tsx
- static/data/home.ts
- types.d.ts
Warnings are still thrown from the ReactMarkdown import. however it builds fine. I will keep looking for a better way to deal with this but as the build doesn't actually have any problems using the component I think it's ok to use. it's safer than alternatives like `dangerouslySetHTML` for rendering markdown.
> Fix build patch

- src/components/content/ColoringBookSection/data.ts
- src/components/content/ColoringBookSection/index.tsx
- src/components/content/DateTimeBox/index.tsx
- src/components/layout/CardGrid/index.tsx
- src/components/layout/HeroHeader/index.tsx
- src/components/layout/PageHeader/index.tsx
- src/components/layout/SectionHeader/index.tsx
- src/components/shapes/WaveBorder/index.tsx
- src/components/ui/ArticleCard/index.tsx
- src/components/ui/Card/index.tsx
- src/components/ui/InfoBanner/index.tsx
- src/components/ui/InfoBox/index.tsx
- src/components/ui/MeetingThumb/index.tsx
- src/components/ui/SmallCard/index.tsx
- src/components/ui/Testimonial/index.tsx
- src/components/ui/ThumbCard/index.tsx
- src/components/utilities/Button/index.tsx
- src/components/utilities/DropdownButton/index.tsx
- src/components/utilities/Highlight/index.tsx
- src/components/utilities/IconLink/index.tsx
- src/components/utilities/Link/index.tsx
- src/components/utilities/ListItem/index.tsx
- src/components/utilities/Markdown/index.tsx
- src/pages/community.tsx
- src/pages/features.tsx
- src/pages/get-started.tsx
- src/pages/index.tsx
- types.d.ts
This follows up sprint 3 with refactoring for easier code reading and editing. The goal is to prep for project completion.
- Code Splitting
- Custom Markdown component to reduce imports
- Minor changes to prop organization
- Component code layout organization
Sprint-4 is focused on the last pieces of functionality and content. 
Code management tasks that will accompany this (and be the focus for the post sprint-4 cleanup) are:
- Error handling (logic with try/catch and conditionals. Rendering with React's ErrorBoundary components
- Better type management
- scope props more with exact possible options (more consistent style) and use ternary variable setting for things like text color etc (so you don't pass a bunch of styles and instead trigger options built in)
- make a more efficient use …
> Sprint 3 cleanup

- src/components/content/CodeExampleSection/data.ts
- src/components/content/CodeExampleSection/index.tsx
- src/pages/get-started.tsx
This PR adds the last bit of get started content. We will be using mp4s for code animations which will use [react player](https://www.npmjs.com/package/react-player) with info boxes sliding in from the right on scroll.
This content will get pretty heavy so it's going to make use of lazy loading.
> setup SearchPullListSection

- src/components/content/TestimonialSection/index.tsx
- src/components/ui/ArticleCard/index.tsx
- src/components/ui/Testimonial/index.tsx
- src/pages/features.tsx
- src/pages/index.tsx
- static/data/features.ts
- static/data/home.ts
Adds Testimonial horizontal scroll layout, better spacing for cards.
> Card Visual and Code Cleanup

- docusaurus.config.js
- src/components/content/FeaturesCarousel/data.ts
- src/components/content/FeaturesCarousel/index.tsx
- src/components/layout/HeroHeader/index.tsx
- src/components/layout/PageHeader/index.tsx
- src/components/ui/ArticleCard/index.tsx
- src/components/utilities/Button/index.tsx
- src/css/main.css
- src/pages/features.tsx
- src/pages/get-started.tsx
- static/data/home.ts
These are all changes from Issue #42
> Style fixes

- src/components/layout/HeroHeader/index.tsx
- src/components/ui/ArticleCard/index.tsx
- src/pages/index.tsx
minor fix to a minor issue that cleans up the console.
> Article card fixes

- src/components/layout/HeroHeader/index.tsx
- src/components/utilities/Button/index.tsx
> Os detect fix

- src/components/content/WelcomeBanner/index.tsx
- src/css/main.css
- src/pages/index.tsx
adds a welcome banner and purple footer to the site.
> Welcome banner

- docs/first-steps.md
- docs/tutorials/installation.md
- docs/tutorials/podman_tutorial.md
- src/components/content/ColoringBookSection/data.ts
- src/components/layout/HeroHeader/index.tsx
- src/components/layout/HeroHeader/installOptions.ts
- src/pages/features.tsx
- src/pages/get-started.tsx
- static/data/community.ts
- static/data/features.ts
- static/data/get-started.ts
- static/data/global.ts
- static/data/home.ts
> Post launch fixes

- getting-started/checkpoint.md
- getting-started/index.md
- getting-started/podman.svg
- getting-started/troubleshooting.md
A number of links from the https://github.com/containers/podman/README.md file are broken.  This moves the contents of the files from the old page to the new one to get the links to not 404.  We will probably want to pretty these up later.
> Add Getting Started Filed to make links happy

- getting-started/installation.md
When I added the files for the "getting-started" directory, I neglected to add the one for the install instructions.
Adding now.
> Add old installation for link breakage fix

- docusaurus.config.js
> Edit docs fix

- .github/workflows/deploy.yml
This reverts commit 3abf72065d027cab7a5ac1bf480f5abb7dadc9c5. as it did not fix the problem.
> Revert "GHA: Fix reference to reusable workflow file"

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Implement a test workflow that reuses the setup_and_build workflow.
Depends on: https://github.com/containers/podman.io/pull/101
> GHA: Add test-build workflow for PRs

- static/data/_testimonials.csv
- static/data/testimonials.ts
same as #95, which i accidentally closed
> fixes typo for Mastodon social in testimonials

- src/components/content/WelcomeBanner/index.tsx
> Fix prominent typo on start page

- sidebars.js
> Add link to tutorials page in sidebar

- src/components/layout/HeroHeader/index.tsx
- Will address #133 (https://github.com/containers/podman.io/issues/133)
- Fix is just making the button font sizes consistent
> Adjust button sizes on front page hero

- static/data/community.ts
We meet in even months not every month.
Fixes #115
@TomSweeneyRedHat PTAL
> fix community meeting date

- static/data/global.ts
This should update the podman version to the current latest.
Bye!
> Update podman version to 4.5.1
